<<<<<<< HEAD
# Generated by Django 4.2.11 on 2025-10-31 14:56
=======
# Generated by Django 4.2.11 on 2025-10-31 10:50
>>>>>>> cc10226e5e890957c257d695e785765b3dc08ce8

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< HEAD
                ("name", models.CharField(blank=True, max_length=100)),
=======
>>>>>>> cc10226e5e890957c257d695e785765b3dc08ce8
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("giving", "Giving Out Candy"),
                            ("out", "Out of Candy"),
                            ("none", "Not Participating"),
                        ],
                        default="giving",
                        max_length=10,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
