# Generated by Django 4.2.11 on 2025-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
